### PR TITLE
Updated POM to fix Maven 3.9 validation issues

### PR DESCRIPTION
**Pull request by stefanoschalkidis**
Hi,

This PR updates the project's pom to fix the validation issue warning in Maven 3.9.

Tested with a local `mvn install` using Maven 3.9.2 and Maven 3.9.5.

Minimum Java version was increased to 8.

- - -
This change is [Reviewable](https://reviewable.io/reviews/DigitalMediaServer/nsis-maven-plugin/10)

### CODE REVIEW

**Comment by Nadahar** [comment]
Thank you, I've been locked out of Github by their stupid forced 2FA "policy" so I've been unable to answer.

I use an older version of Maven to avoid the stupid "forced HTTPS" rule they made at one point, which breaks all kind of things. Thus, I have no idea what this "validation" is about. A quick search seemed to indicate that it only generates warnings, and doesn't actually cause a build problem..?

Backwards compatibility is important to me, so artificially requiring a more recent Maven version isn't very appealing. Is there some good reason for this bump? The same goes for the Java 8 requirement - I'm still using Java 7 myself, so I'm wondering if there's a good reason to do this?

**Comment by stefanoschalkidis** [comment]
No problem and thanks for getting back to me.

I also do not know what this "validation" contains in detail but it seems updating the pom is most of the times enough to get rid of the warnings. The warnings themselves do not cause a build problem. In the [Release Notes](https://maven.apache.org/docs/3.9.2/release-notes.html#notable-new-features) of version 3.9.2 it says that plugins not passing the validation may not work under Maven 4. I haven't tried Maven 4 yet though, waiting for a stable release first.

Yes, I actually bumped the Maven version to 3.8.1 due to the CVE, but if required for backwards compatability this could be decreased again. The bump to Java 8 was because I thought Java 7 was not maintained anymore. A quick search revealed that there are still active builds, so this can be decreased again of course.

Let me know how you would like to proceed with this.

Thanks

**Comment by Nadahar** [comment]
I would prefer to get rid of the warning while stile being compatible with older versions of both Maven and Java. From what you explain it sounds likely to me that this could be achievable by simply reverting some of the changes.

I'm not sure how many of the dependency version bumps that are really needed - I would prefer to only make as few changes as possible while still achieving the goal. In general I don't increase versions unless there's a good reason. I'm getting increasingly tired of CVEs because if you dig into them, most turn out to be very niche and very unlikely to be relevant for most use-cases. I also don't consider "denial of service" a "security issue" for most software. Not everything is a web server. Regardless, my point is that I don't bump stuff because of CVEs unless I know/find that the particular CVE is a "real problem".

An added bonus would be if I didn't have to invest the time to really understand the Maven validation stuff - since it's highly likely to be more of the stuff end up breaking things for very little benefit (they _will_ decide to enforce it at one point - they always do).

If you would do the necessary changes, I could try to build with my ancient software stack, and if it still works I think we're good to go.

**Comment by stefanoschalkidis** [comment]
Ok, I found time to look at it again and the only changes actually required to get rid of the warnings are to add provided scope to the maven plugins listed as dependencies. Should I update the current PR where I have listed all deps at the top or do you prefer a PR with the current structure of the pom (main branch)?

**Comment by Nadahar** [comment]
It doesn't really matter where the dependencies are placed, but I'd prefer if the diff is as small as possible so that it's easy to evaluate the changes. As such, pure "esthetic" changes are preferable to leave out. You don't need to create a new PR in any case - just add commits and I'll squash it at merge.

I thought `provided` meant that Maven didn't care about fetching the dependencies, but I might remember wrong (it's been a while since I've fought with Maven). Are you sure that `provided` will work on a system where the artifacts aren't already cached?

**Comment by Nadahar** [comment]
What exactly are the validation warnings? Could you paste them?

**Comment by stefanoschalkidis** [comment]
Yes, sure, here is the verbose message:

```
Plugin issue(s):
[WARNING]    * Plugin mixes multiple Maven versions: [3.5.4, 3.0]
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-builder-support:3.5.4, org.apache.maven:maven-model-builder:3.5.4, org.apache.maven:maven-artifact:3.0, org.apache.maven:maven-core:3.5.4, org.apache.maven:maven-repository-metadata:3.5.4, org.apache.maven:maven-plugin-api:3.5.4, org.apache.maven:maven-resolver-provider:3.5.4, org.apache.maven:maven-settings:3.5.4, org.apache.maven:maven-model:3.5.4, org.apache.maven:maven-settings-builder:3.5.4]
```

I had read that some maintainers had to update their deps too to get rid of the warnings, so I did everything in one go which was a bit premature.

Yes, you are right about the provided scope. I think in the case for a plugin these deps are provided by the maven instance running the plugin but I have not found a clear explanation for this. Even in the official [guide](https://maven.apache.org/guides/plugin/guide-java-plugin-development.html) it does not say why the scope is set to provided.

I've updated the PR. Let me know if you need anything else.

**Comment by Nadahar** [comment]
I'll have to look at it more tomorrow. I suspect that the plugins claims should be `provided` is "a part of Maven" as as such is always available if Maven is. It would make "provided" make sense for them.

**Comment by Nadahar** [comment]
Maven has never been very good at documentation, and this seems to be no exception. By simply omitting to explain _why_ they "require" things to be a certain way, it's hard to know how to comply.

What is extra inconvenient is that when I try to build the plugin (both `package` and `verify`) using Maven ´3.9.5´, I get no warnings at all. I can't really be necessary to build the plugin and then use it in another project just to see the warning messages...?

It also seems like they haven't quite decided what the "rules" are going to be, since I read that the warnings have been moderated from `3.9.2` to `3.9.3`. Maybe it's a bit premature to try to figure this out - that it's better to wait until _they_ decide how they want it.

`org.apache.maven:maven-artifact` that the warning complains about using version `3.0` isn't even defined in the POM, so that must be some transitive dependency. Am I then supposed to declare it just so that the "validation" can be satisfied? I also have no idea what the consequences, if any, of these things are. If these are in fact "special artifacts" that is provided by the running Maven instance, one would think that the version specifications would be irrelevant - that whatever Maven version was being used dictated which plugin versions would be used.

**Comment by Nadahar** [comment]
@stefanoschalkidis I can't get these warnings no matter how hard I try (with Maven `3.9.5`). I've now tried to build a project that uses this plugin, and nothing. Is it something special I must do to get the warning, or is it possible that they have revised the "validation rules" in `3.9.5`? Could you try with `3.9.5`?

**Comment by stefanoschalkidis** [comment]
Ok, it looks like the Maven `3.9.5` silenced the warning. You can still have it displayed with the validation property:

```
mvn -Dmaven.plugin.validation=verbose package
```

When I built the updated plugin I used the OS' Maven which was `3.8.7` and thus had no warnings there. I just reran the unmodified plugin build with Maven `3.9.5` using the command above and I get the following warnings:

```
[WARNING] 
[WARNING] Plugin [INTERNAL, EXTERNAL] validation issues were detected in following plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-jar-plugin:3.1.0
[WARNING]   Plugin EXTERNAL issue(s):
[WARNING]    * Plugin should declare Maven artifacts in `provided` scope. If the plugin already declares them in `provided` scope, update the maven-plugin-plugin to latest version. Artifacts found with wrong scope: [org.apache.maven:maven-artifact:3.0, org.apache.maven:maven-plugin-api:3.0, org.apache.maven:maven-core:3.0]
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.7.0
[WARNING]   Plugin EXTERNAL issue(s):
[WARNING]    * Plugin should declare Maven artifacts in `provided` scope. If the plugin already declares them in `provided` scope, update the maven-plugin-plugin to latest version. Artifacts found with wrong scope: [org.apache.maven:maven-artifact:3.0, org.apache.maven:maven-plugin-api:3.0, org.apache.maven:maven-core:3.0]
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.1.0
[WARNING]   Declared at location(s):
[WARNING]    * org.digitalmediaserver:nsis-maven-plugin:1.0.4 (pom.xml) @ line 226
[WARNING]   Plugin EXTERNAL issue(s):
[WARNING]    * Plugin should declare Maven artifacts in `provided` scope. If the plugin already declares them in `provided` scope, update the maven-plugin-plugin to latest version. Artifacts found with wrong scope: [org.apache.maven:maven-plugin-api:3.0, org.apache.maven:maven-core:3.0, org.apache.maven:maven-model:3.0]
[WARNING]   Mojo EXTERNAL issue(s):
[WARNING]    * Mojo resources:resources (org.apache.maven.plugins.resources.ResourcesMojo)
[WARNING]      - Mojo implements `Contextualizable` interface from Plexus Container, which is EOL.
[WARNING]    * Mojo resources:testResources (org.apache.maven.plugins.resources.TestResourcesMojo)
[WARNING]      - Mojo implements `Contextualizable` interface from Plexus Container, which is EOL.
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-plugin-plugin:3.5.2
[WARNING]   Declared at location(s):
[WARNING]    * org.digitalmediaserver:nsis-maven-plugin:1.0.4 (pom.xml) @ line 180
[WARNING]   Plugin EXTERNAL issue(s):
[WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
[WARNING]   Mojo EXTERNAL issue(s):
[WARNING]    * Mojo plugin:helpmojo (org.apache.maven.plugin.plugin.HelpGeneratorMojo)
[WARNING]      - Parameter 'local' uses deprecated parameter expression '${localRepository}': ArtifactRepository type is deprecated and its use in Mojos should be avoided.
[WARNING]    * Mojo plugin:descriptor (org.apache.maven.plugin.plugin.DescriptorGeneratorMojo)
[WARNING]      - Parameter 'local' uses deprecated parameter expression '${localRepository}': ArtifactRepository type is deprecated and its use in Mojos should be avoided.
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-surefire-plugin:2.20
[WARNING]   Declared at location(s):
[WARNING]    * org.digitalmediaserver:nsis-maven-plugin:1.0.4 (pom.xml) @ line 221
[WARNING]   Plugin EXTERNAL issue(s):
[WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
[WARNING]   Mojo EXTERNAL issue(s):
[WARNING]    * Mojo surefire:test (org.apache.maven.plugin.surefire.SurefirePlugin)
[WARNING]      - Parameter 'localRepository' uses deprecated parameter expression '${localRepository}': ArtifactRepository type is deprecated and its use in Mojos should be avoided.
[WARNING] 
[WARNING] 
[WARNING] Fix reported issues by adjusting plugin configuration or by upgrading above listed plugins. If no upgrade available, please notify plugin maintainers about reported issues.
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [NONE, INLINE, SUMMARY, BRIEF, VERBOSE]
[WARNING]
```

It seems that in addition to the provided scope some plugins should be updated. I will have a look at this later and get back to you.

**Comment by Nadahar** [comment]
Using
```
mvn -Dmaven.plugin.validation=verbose package
```
...makes it list a number of warnings similar to those you pasted above. But, none of them seems to apply to nsis-maven-plugin, but to its dependencies. I assume that upgrading these would resolve some issues, but I'm very reluctant at potentially breaking builds with older version merely to remove some warnings.

Maybe upgrading the plugins won't break building with older Maven versions, but it seems like a tedious job actually testing and making sure of this.

I still don't see any warnings that applies to _this_ plugin though.

**Comment by Nadahar** [comment]
Building the project that use this plugin with `-Dmaven.plugin.validation=verbose` specified produces the warnings you initially specified. However, it seems like the guys at Apache is walking down a path of "scorched earth" with Maven 4.0 where they will break all kind of things. All Maven 2 stuff seems to no longer work, and it turns out that a lot of things still use some of these APIs etc.

I've installed Maven 4 alpha 8, and this plugin still builds without any warnings or issues. When I try to build the project that use this plugin though, all kind of other plugins break (most of them made by Apache themselves), so it's obvious to me that Maven 4 will require "updated" plugins all across and backwards compatibility or even just the ability to build older snapshots of things will be a impossible for those that use it.

I'm thus tempted to not do anything to this plugin now, and if it turns out to be necessary in the future, make a separate branch for "Maven 4" where dependencies are updated and backwards compatibility is out the window. It could the be released to central as a `4.x` version range for example. But, I'd rather wait until it is actually necessary.

**Comment by stefanoschalkidis** [comment]
Sounds good to me. Let's make a `4.x` version of the plugin if required once Maven `4` is released and let's keep the current release as it is for now.

Thanks a lot for looking into this.

**Comment by Nadahar** [comment]
@stefanoschalkidis I did just make a new release `1.0.4` where I added a parameter where you can turn off compression (for better speed when testing). Sonatype complained a lot about all the "potential vulnerabilities" when I wanted to publish the release, so I updated some of the dependencies to the latest versions that support Java 7. I don't think that it will make a difference with regards to Maven 4, but it should get rid of some of the claimed vulnerabilities (although those I checked turned out to be completely irrelevant for this plugin).

So, in case you care to get a bit more updated dependencies, `1.0.4` should be available within 4-5 hours or so (Maven Central takes a while to actually effectuate a release).

**Comment by stefanoschalkidis** [comment]
@Nadahar Thanks for letting me know. I just tested the latest version in my build pipeline and everything works as expected.

Yes, the warnings remain, but we'll tackle them once requirements around Maven `4` start to clear up.

Thanks again.

**Comment by Nadahar** [comment]
@stefanoschalkidis Not that I think it will make a difference for your use, but I've made another tiny change (to what I did in `1.0.4`) and released `1.0.5`.

**Pull request closed without merging**
