### PR TITLE
Feature - search environment PATH for makensis

### PR DESCRIPTION
**Pull request by adamretter**
If `makensis` cannot be found, perhaps because it has not been configured explicitly in conf.xml and is not present in the CWD from where Maven is launched... then we can check the system's PATH to see if we can find it.

This can simplify use of the plugin when `makensis` is already available executable via the System's PATH environment variable.

---
This change is [Reviewable](https://reviewable.io/reviews/digitalmediaserver/nsis-maven-plugin/4)

### CODE REVIEW

**Comment by Nadahar** [comment]
Thank you for the contribution. I haven't worked on this for quite a while, so my memory is quite blurry, but I thought that it already did this as it is..?

I'm pretty sure that I've used it on Linux with package manager installed makensis. Can you shed some light to refresh my memory, in what scenario/OS are you experiencing this? According to the [documentation I've written](https://github.com/DigitalMediaServer/nsis-maven-plugin/blob/master/README.md) for `makensisExecutable`, this is the behavior if it's not specified: 
> The path of the makensis executable to use. The default assumes that makensis can be found in the OS path.

**Comment by adamretter** [comment]
@Nadahar Indeed reading your documentation, that was the behaviour I expected. However when I checked the code that is not the behaviour that was present, it seems that `Paths.get(makensisExecutable)` is used. Exactly where and how that resolves is somewhat variable depending on your OS.

I am using a makensis which I have installed manually, and then added to the environment's PATH variable.

**Comment by Nadahar** [comment]
What OS?

**Comment by adamretter** [comment]
@Nadahar Ah right yes... both Mac and Linux.

**Comment by Nadahar** [comment]
I'm currently having some issues with Eclipse not accepting `maven-plugin-plugin` when I try to import the project. In my old Eclipse installation this could be solved by installing "Eclipse Plug-in Development Environment" from M2E's "catalog", but in the newer version of Eclipse that I'm running now (was forced to because of some other issues) this is nowhere to be found.

So, until I've figured out this BS, I can't dig into the plugin. I do have a suspicion though. It might be that it's the combination of using `autoNsisDir` in combination with an OS path located `makensis`. Could that make sense?

My theory is that when not specifying a path for `makensis` it is simply executed unqualified, which will make the OS resolve it from the path automatically. But, that means that the plugin never really knows the location of `makensis`, so it can't use it to infer the "NSIS folder". I don't use `autoNsisDir` in my project, so I probably wouldn't have come across this combination.

**Comment by adamretter** [comment]
> when not specifying a path for makensis it is simply executed unqualified, which will make the OS resolve it from the path automatically

When not specifying a path for `makensis`, the problem I saw was that `.toRealPath()` throws an IOException, because the file does not exist (in the CWD), and that was happening even before my previous PR AFAIK

**Comment by Nadahar** [comment]
@adamretter My memory won't cooperate. I have a "strong hunch" that I at some point "simplified" that code by removing a `Files.exists()` call that was probably done before the `toRealPath()` call. I can't find any "proof" in the commit history though. Not that it matters that much, I'm just so convinced that I have done just what isn't working now.

The important thing is to make it work now. These are my thoughts:

The plus side of "manually resolving" OS path items is that allows us to automatically resolve NSISDIR also when `makensis` is on the OS path. However, I am worried (with all the different environments out there) that "emulating" what the OS does won't always produce the same results as the OS does itself.

Maybe the best compromise is to not resolve the path unless `autoNsisDir` is true, to retain 100% OS compliant search behavior when we can, but to "resolve it manually" when `autoNsisDir` is true to be able to use it for that..? Maybe it's even better to not alter `makensisExecutable` at all if the file isn't found, and only "resolve it manually" for use with the `autoNsisDir` logic?

Is the OS path "resolution" code written for this, or is it a copy of a code used elsewhere that has been well tested "in the wild"? I have some code that does this in another project that has been relatively well battle tested and seems to behave well. I haven't compared the logic of the two algorithms, so they might do it the exact same way for all I know, but I would just like to know what is the "safer" algorithm to go with.

**Comment by adamretter** [comment]
> However, I am worried (with all the different environments out there) that "emulating" what the OS does won't always produce the same results as the OS does itself.

I haven't found anything build into Java that can resolve files against the PATH for you. It seems this is something you have to calculate manually.

> Maybe the best compromise is to not resolve the path unless autoNsisDir is true, to retain 100% OS compliant search behavior

I am not sure what this "OS search behavior" that you describe is? At the moment it only checks the CWD. It would seem to me if you can't find makensis in the first place, it doesn't really matter whether autoNsDir is true or false... it's not going to work. Maybe I am misunderstanding though? We do have `autoNsDir` implicitly set to true in our projects, but I can't remember if that's just because it's the default of the plugin.

> Is the OS path "resolution" code written for this, or is it a copy of a code used elsewhere that has been well tested "in the wild"?

It was written for this app as it seemed a very simple thing ;-)

**Comment by Nadahar** [comment]
> I am not sure what this "OS search behavior" that you describe is

Ah, that explains it. The "trick" that was used originally, and that I must have broken at some point without noticing, is not specifying a path at all. When you do that, so that only `makensis` (or some other file name) is in `makensisExecutable`, and you *don't* "resolve it" using `toRealPath()`, `toAbsolutePath()` or similar, the OS will search the path by itself. That is how the OS path works "normally", and this goes here as well. But, as soon as you "resolve" it to a full path, instead of just the filename, this stops working and it will only look in the current working directory.

**Comment by adamretter** [comment]
> and you don't "resolve it" using toRealPath(), toAbsolutePath() or similar, the OS will search the path by itself. That is how the OS path works "normally", and this goes here as well. 

Hmmm... I haven't seen that documented anywhere in the Javadocs for java.io ... is that platform specific to Windows perhaps?

**Comment by Nadahar** [comment]
No, I've used this "technique" many times, and it works on all OS'es as far as I know. I don't think java.io would document it, because this isn't handled by Java. It won't work for other file types than executables, just like the "normal rules" for OS path. So, you can't do this when opening a file for reading with an `InputStream` for example, but you can use it if you spawn an external `Process` etc.

**Comment by adamretter** [comment]
Interesting!

Okay, so how do we move forward?

**Comment by Nadahar** [comment]
I'm trying to do get one of my Linux VM's set up for some testing. It's been too long since I dealt with this, so I need to do some testing to verify my claims. If things work as I claim, I think the best solution is to only "manually resolve" it for the "autoNSIS" functionality.

I'll come up with a suggestion, and assuming that it works for me, I'll ask you to test it as well if that's ok, before making a release.

**Comment by Nadahar** [comment]
I've made a suggested fix. It turns out the OS path stuff was a bit more complicated (I didn't remember the details, just had a hunch that there were complications), so I ended up copying my own code from another project and simplified it to be suitable here.

It can be found in branch [fixOSPath](https://github.com/DigitalMediaServer/nsis-maven-plugin/tree/fixOSPath).

https://github.com/DigitalMediaServer/nsis-maven-plugin/compare/master...DigitalMediaServer:fixOSPath

I was planning to upload a snapshot version so testing it would be easy, but it seems like there are some issues with my account at Sonatype. I've contacted them, but I'm waiting for reply, so for now I can't upload anything to Sonatype or Maven Central.

I've done some basic testing on Fedora, and it seems to work well there.

**Comment by Nadahar** [comment]
@adamretter Sonatype has straightened out my permission issues, and I've pushed '1.0.3-SNAPSHOT' to the snapshot repository. I'd appreciate if you could test and confirm whether this works for you.

To use the snapshot version, you must temporarily add the following to your POM:
```xml
<pluginRepositories>
	<pluginRepository>
		<id>ossrh-snapshot</id>
		<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
	</pluginRepository>
</pluginRepositories>
```

If you already have a `<pluginRepositories>` section you obviously add the new `<pluginRepository>` to that section instead.

In addition, just change the artifact version to `1.0.3-SNAPSHOT`, and then build as normal.

Don't keep the plugin repository in your POM unless you need it there for other reasons. Each repository makes Maven builds slower, and this repository can be slow to respond at times.

Please let me know if it work fine for you. My tests have been fine.

**Comment by Nadahar** [comment]
This has been replaced by #6.

**Pull request closed without merging**
